### PR TITLE
Add Animesh Funcs and some OBJECT_* flags(36~38)

### PR DESCRIPTION
**Pull request by PellSmit**
Added Animesh Functions and OBJECT_* flags:
llStartObjectAnimation(string anim);
llStopObjectAnimation(string anim);
list llGetObjectAnimationNames();
integer OBJECT_CREATION_TIME = 36;
integer OBJECT_SELECT_COUNT = 37;
integer OBJECT_SIT_COUNT = 38;

### CODE REVIEW

**Comment by PellSmit** [comment]
I'll upload binary after Ray answers my comment.

**Comment by raysilent** [comment]
Glad you found these guys! I was looking at a wrong place I guess

**Comment by PellSmit** [comment]
LSLForge binary file for Mac:
https://www.icloud.com/iclouddrive/0iLnKdWOH86hW0GVQWaqYSgqQ#LSLForge

**Comment by raysilent** [comment]
Hey Pell, may we first update the version number? And you recompile
everything?

**Comment by raysilent** [comment]
Could you please pull 0.1.9.6 branch and compile it?

**Comment by PellSmit** [comment]
Ok, here:
https://www.icloud.com/iclouddrive/0OjQw-G_9SxTHlnVhm8k5istg#LSLForge

**Pull request merged**
