### PR TITLE
Pell smit/0.1.9.3

### PR DESCRIPTION
**Pull request by PellSmit**
Native module binary for Mac

### CODE REVIEW

**Comment by pakkio** [comment]
Hi PellSmit, I wonder if you have a binary mac version of lslforge with the patches needed to be used in OpenSim (too many parenthesis). I tried to compile lslforge on my mac but without success, I had to change the ghci compiler to compile for 32-bit (but unsure it was the right solution), but then had was not able to compile the HaXML 1.19.6
I was able to patch lslforge under windows but I normally work with a mac book pro :)

Getting ld: warning: could not create compact unwind for .LFB3: non-standard register 5 being saved in prolog
ld: in /Library/Frameworks/GHC.framework/Versions/610/usr/lib/ghc-6.10.1/libffi.a(darwin.o), sectionForAddress(0x264) address not in any section for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by PellSmit** [comment]
@pakkio, I don't know what the error message means, only know we can't build LSLForge on macOS newer than Lion.
LSLForge needs GHC 6.10 but we need Snow Leopard or earlier to run it.
I always build LSLForge using the first MacBook Pro(11 years old!), doesn't work with Lion or later.

If you want to build LSLForge on newer GHC, refer to  https://github.com/raysilent/lslforge/issues/20 .
@simon-nicholls is working around it.

**Comment by simon-nicholls** [comment]
I'm travelling at the moment, though I can offer some build advice in the meantime. I estimate I'll be making a pull request the week after next.

The easiest approach would be to install "Stack" if you don't have it already, using Homebrew or the method described over at the [Stack homepage](https://www.haskellstack.org/).

Then clone my master branch, go to the haskell subdirectory, and enter `stack install` to build and install the LSLForge binary to `~/.local/bin`. You will need to use `stack setup` beforehand, if you have freshly installed Stack, or don't have the relevant compiler already set up.

**Comment by pakkio** [comment]
Thanks, @simon-nicholls that system appears very human and dumb-proof. I will definitely stick to stack :) Will test it in Linux as well. Now maybe I can be able to use lslForge for OpenSimulator as well.

**Pull request merged**
